import type { Metadata } from 'next';
import Link from 'next/link';
import { Suspense } from 'react';
import Header from '../../components/common/Header';
import Footer from '../../components/common/Footer';
import WeddingTimelineBuilder from '../../components/wedding/WeddingTimelineBuilder';

const faqs = [
  ['How long should a wedding day timeline be?', 'Most timelines run from hair and makeup through the send-off, usually 10 to 14 hours. Build in time for travel and vendor setup.'],
  ['What time should hair and makeup start?', 'Start from the ceremony time and work backward. Allow enough time for every person, then add a buffer before getting dressed.'],
  ['Can I print my wedding timeline?', 'Yes. Edit the free timeline, download it as a PNG, or choose Save as PDF from the print dialog.'],
  ['Is this wedding timeline maker free?', 'Yes. It is free to use and does not require an account.'],
  ['Should we do a first look?', 'A first look can move portraits before the ceremony and create more reception time. Without one, reserve time after the ceremony for photos.'],
  ['How much buffer time should I add?', 'Add at least 10 to 15 minutes around travel, getting dressed, family photos, and transitions between the ceremony and reception.'],
];

export const metadata: Metadata = { title: 'Free Wedding Day Timeline Template & Maker (Printable)', description: 'Free editable wedding day timeline template. No signup—customize your wedding schedule and download it as a PNG or PDF.', alternates: { canonical: 'https://www.freeschedulemaker.com/wedding-day-timeline-maker' }, openGraph: { title: 'Free Wedding Day Timeline Template & Maker (Printable)', description: 'Create, edit, print, and share a free wedding day timeline.', url: 'https://www.freeschedulemaker.com/wedding-day-timeline-maker', type: 'website' }, twitter: { card: 'summary_large_image', title: 'Free Wedding Day Timeline Template & Maker (Printable)', description: 'Create, edit, print, and share a free wedding day timeline.' } };

export default function WeddingDayTimelineMakerPage() {
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };
  const appSchema = { '@context': 'https://schema.org', '@type': 'WebApplication', name: 'Free Wedding Day Timeline Template & Maker', applicationCategory: 'BusinessApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } };
  const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.freeschedulemaker.com/' }, { '@type': 'ListItem', position: 2, name: 'Wedding Day Timeline Maker', item: 'https://www.freeschedulemaker.com/wedding-day-timeline-maker' }] };
  return <main className="min-h-screen bg-slate-50"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(appSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><Header />
    <section className="border-b border-slate-200 bg-white px-6 py-14"><div className="mx-auto max-w-5xl"><p className="mb-4 text-sm font-bold text-indigo-600">Free printable wedding timeline</p><h1 className="text-4xl font-extrabold tracking-tight text-slate-900 md:text-5xl">Wedding Day Timeline Template</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-600">Start with a real wedding day schedule, make every time block your own, then share a clean itinerary with your wedding party and vendors. Free, editable, and no signup required.</p><a href="#builder" className="mt-7 inline-flex rounded-lg bg-indigo-600 px-6 py-3 font-bold text-white hover:bg-indigo-700">Use the free wedding timeline</a></div></section>
    <div className="mx-auto max-w-7xl px-4 sm:px-6"><Suspense fallback={<div className="py-12 text-slate-600">Loading timeline…</div>}><WeddingTimelineBuilder /></Suspense></div>
    <section className="border-y border-slate-200 bg-white px-6 py-14"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-bold text-slate-900">Sample wedding day timeline</h2><p className="mt-3 text-slate-600">4 PM ceremony with a first look. Adjust this example to your venue and vendors.</p><div className="mt-6 overflow-hidden rounded-xl border border-slate-200"><table className="w-full text-left text-sm"><tbody>{[['8:00 AM','Hair and makeup begins'],['10:30 AM','Photographer and videographer arrive, detail shots'],['12:00 PM','Lunch for the wedding party'],['1:00 PM','Get dressed'],['2:00 PM','First look'],['2:20 PM','Couple portraits'],['2:50 PM','Wedding party portraits'],['3:15 PM','Family formals'],['3:30 PM','Guests arrive and are seated'],['4:00 PM','Ceremony'],['4:30 PM','Cocktail hour'],['5:30 PM','Grand entrance'],['5:45 PM','Dinner'],['6:45 PM','Toasts'],['7:15 PM','First dance and parent dances'],['7:45 PM','Cake cutting'],['8:00 PM','Open dancing'],['10:00 PM','Last dance and send-off']].map(([time,item]) => <tr key={time} className="border-b last:border-0"><td className="w-28 bg-slate-50 p-3 font-bold text-slate-800">{time}</td><td className="p-3 text-slate-600">{item}</td></tr>)}</tbody></table></div></div></section>
    <section className="mx-auto max-w-4xl px-6 py-14 text-slate-600"><h2 className="text-3xl font-bold text-slate-900">How to make a wedding timeline that works</h2><div className="mt-6 space-y-5 leading-7"><p>Begin with the ceremony time, then work backward for getting ready, travel, photography, and guest arrival. Work forward for cocktail hour, dinner, toasts, dancing, and the exit. A timeline is not a promise that every minute will be perfect; it is a shared plan that keeps the people making the day happen on the same page.</p><p>Getting ready often takes longer than expected because hair, makeup, food, details, and photos all compete for the same room. Give the photographer time to capture invitation suites, rings, attire, and florals before you are dressed. If you are travelling between locations, add a buffer for loading cars, parking, and finding the right entrance.</p><p>A first look lets you complete couple, wedding-party, and many family portraits before guests arrive. That creates more breathing room after the ceremony. Without a first look, reserve a longer cocktail hour and make sure family members know exactly where to meet. Either choice works when the plan matches your priorities.</p><p>At the reception, protect the moments you care about: a calm entrance, dinner, toasts, dances, cake, and a final song. Ask your venue and caterer how long service really takes, and ask your DJ or band when they need cues. Add 10 to 15 minutes between major moments; those small buffers absorb late arrivals and give you a chance to enjoy the day.</p></div><h2 className="mt-12 text-3xl font-bold text-slate-900">How to use this template</h2><ol className="mt-5 list-decimal space-y-2 pl-5"><li>Edit each timeline block and change the times for your day.</li><li>Add venue, travel, and buffer details.</li><li>Share the timeline with your photographer, DJ, and wedding party.</li><li>Download it as a PNG or save it as a PDF to print.</li></ol><h2 className="mt-12 text-3xl font-bold text-slate-900">Wedding timeline FAQs</h2><div className="mt-5 space-y-4">{faqs.map(([q,a]) => <div key={q}><h3 className="font-bold text-slate-900">{q}</h3><p className="mt-1">{a}</p></div>)}</div><h2 className="mt-12 text-2xl font-bold text-slate-900">Related planning tools</h2><p className="mt-3"><Link className="font-bold text-indigo-600 hover:underline" href="/tools">Browse all scheduling tools</Link> or <Link className="font-bold text-indigo-600 hover:underline" href="/templates">explore printable templates</Link>.</p></section><Footer /></main>;
}
