import { BuilderVariantConfig, BuilderVariantId } from '../types/schedule';

export const BUILDER_VARIANTS: Record<BuilderVariantId, BuilderVariantConfig> = {
  default: {
    id: 'default',
    title: 'Free Schedule Maker',
    description: 'The easiest free online schedule builder. Build, color-code, and download your schedule instantly.',
    audience: 'Everyone',
    defaultEventTitle: 'Event',
    primaryActionLabel: 'Add Event',
    templateType: 'default',
    eventLabels: {
      title: 'Event Name',
      person: 'Person (Optional)',
      location: 'Location (Optional)',
      category: 'Category (Optional)',
    },
    suggestedCategories: ['Personal', 'Work', 'Education', 'Fitness', 'Other'],
    relatedTools: ['weekly', 'university', 'rota'],
  },
  weekly: {
    id: 'weekly',
    title: 'Weekly Schedule Maker',
    description: 'Organize your weekly schedule, chores, tasks, and appointments with ease.',
    audience: 'Everyone',
    defaultEventTitle: 'Task / Event',
    primaryActionLabel: 'Add Event',
    templateType: 'default',
    eventLabels: {
      title: 'Event Name',
      person: 'Who is involved',
      location: 'Location',
      category: 'Category',
    },
    suggestedCategories: ['Work', 'Personal', 'Health', 'Social', 'Finance', 'Urgent'],
    relatedTools: ['university', 'rota', 'employee'],
  },
  university: {
    id: 'university',
    title: 'University Timetable Maker',
    description: 'Create class timetables for lectures, labs, tutorials, breaks, and exams.',
    audience: 'Students & Professors',
    defaultEventTitle: 'Class / Lecture',
    primaryActionLabel: 'Add Class',
    templateType: 'university',
    eventLabels: {
      title: 'Course or Class Name',
      person: 'Teacher Name',
      location: 'Room Number',
      category: 'Lecture Type',
    },
    suggestedCategories: ['Lecture', 'Lab', 'Tutorial', 'Break', 'Exam', 'Seminar'],
    relatedTools: ['revision', 'weekly', 'default'],
  },
  rota: {
    id: 'rota',
    title: 'Rota Maker',
    description: 'Create staff rota schedules for employees, shifts, teams, and weekly work planning.',
    audience: 'Managers & Business Owners',
    defaultEventTitle: 'Shift',
    primaryActionLabel: 'Add Shift',
    templateType: 'rota',
    eventLabels: {
      title: 'Shift Name',
      person: 'Employee Name',
      location: 'Work Location',
      category: 'Shift Type',
    },
    suggestedCategories: ['Morning Shift', 'Day Shift', 'Evening Shift', 'Night Shift', 'On-Call', 'Break'],
    relatedTools: ['employee', 'shift', 'weekly'],
  },
  employee: {
    id: 'employee',
    title: 'Employee Schedule Creator',
    description: 'Organize work hours, assign roles, and build schedules for your employees.',
    audience: 'HR & Managers',
    defaultEventTitle: 'Work Session',
    primaryActionLabel: 'Add Work Session',
    templateType: 'employee',
    eventLabels: {
      title: 'Task or Role',
      person: 'Employee Name',
      location: 'Department',
      category: 'Shift Block',
    },
    suggestedCategories: ['Sales', 'Support', 'Kitchen', 'Reception', 'Management', 'Break'],
    relatedTools: ['rota', 'shift', 'weekly'],
  },
  shift: {
    id: 'shift',
    title: 'Shift Schedule Generator',
    description: 'Quickly generate shifts for rotation, weekly rosters, and operations.',
    audience: 'Operations Managers',
    defaultEventTitle: 'Shift',
    primaryActionLabel: 'Add Shift',
    templateType: 'shift',
    eventLabels: {
      title: 'Shift Title',
      person: 'Staff Assigned',
      location: 'Station / Line',
      category: 'Shift Category',
    },
    suggestedCategories: ['First Shift', 'Second Shift', 'Third Shift', 'Overtime', 'Training', 'Break'],
    relatedTools: ['rota', 'employee', 'weekly'],
  },
  revision: {
    id: 'revision',
    title: 'Revision Timetable Maker',
    description: 'Plan study sessions, subjects, exam preparation, and revision blocks.',
    audience: 'Students & Teachers',
    defaultEventTitle: 'Study Session',
    primaryActionLabel: 'Add Study Session',
    templateType: 'revision',
    eventLabels: {
      title: 'Subject or Topic',
      person: 'Tutor (Optional)',
      location: 'Study Location',
      category: 'Priority',
    },
    suggestedCategories: ['High Priority', 'Medium Priority', 'Low Priority', 'Math', 'Science', 'History', 'Languages', 'Practice Exam'],
    relatedTools: ['university', 'weekly', 'default'],
  },
};
