import Link from 'next/link';
import { Suspense } from 'react';
import Header from '../common/Header';
import Footer from '../common/Footer';
import WeddingTimelineBuilder from './WeddingTimelineBuilder';

export default function WeddingSupportingPage({ title, intro, sample, guide, faqs, templateIds, defaultTemplate, ceremony = false }: { title: string; intro: string; sample: [string,string][]; guide: string; faqs: [string,string][]; templateIds: string[]; defaultTemplate: string; ceremony?: boolean }) {
  const slug = ceremony ? 'wedding-ceremony-timeline-maker' : 'wedding-reception-timeline-maker';
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) };
  return <main className="min-h-screen bg-slate-50"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context':'https://schema.org','@type':'WebApplication',name:title,applicationCategory:'BusinessApplication',operatingSystem:'All',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'} }) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://www.freeschedulemaker.com/'},{'@type':'ListItem',position:2,name:title,item:`https://www.freeschedulemaker.com/${slug}`}] }) }} /><Header /><section className="bg-white px-6 py-14 border-b border-slate-200"><div className="max-w-5xl mx-auto"><p className="text-sm font-bold text-indigo-600">Free printable wedding template</p><h1 className="mt-3 text-4xl md:text-5xl font-extrabold text-slate-900">{title}</h1><p className="mt-5 max-w-3xl text-lg text-slate-600 leading-relaxed">{intro}</p><a href="#builder" className="inline-flex mt-7 rounded-lg bg-indigo-600 px-6 py-3 font-bold text-white">Use the free template</a></div></section><div className="max-w-7xl mx-auto px-4 sm:px-6"><Suspense fallback={<div className="py-10">Loading…</div>}><WeddingTimelineBuilder templateIds={templateIds} defaultTemplate={defaultTemplate} /></Suspense></div><section className="bg-white border-y border-slate-200 px-6 py-14"><div className="max-w-4xl mx-auto"><h2 className="text-3xl font-bold text-slate-900">Sample {ceremony ? 'ceremony' : 'reception'} timeline</h2><ol className="mt-6 space-y-2">{sample.map(([time,item])=><li key={time} className="flex gap-4 border-b pb-2"><strong className="w-24 text-slate-900">{time}</strong><span className="text-slate-600">{item}</span></li>)}</ol><h2 className="mt-12 text-3xl font-bold text-slate-900">{ceremony ? 'Planning the ceremony order' : 'How long does each reception part take?'}</h2><p className="mt-4 leading-7 text-slate-600">{guide}</p><h2 className="mt-12 text-3xl font-bold text-slate-900">Frequently asked questions</h2><div className="mt-5 space-y-4">{faqs.map(([q,a])=><div key={q}><h3 className="font-bold text-slate-900">{q}</h3><p className="mt-1 text-slate-600">{a}</p></div>)}</div><h2 className="mt-12 text-2xl font-bold text-slate-900">Related wedding tools</h2><p className="mt-3 text-slate-600"><Link className="font-bold text-indigo-600" href="/wedding-day-timeline-maker">Wedding day timeline</Link> · <Link className="font-bold text-indigo-600" href={ceremony ? '/wedding-reception-timeline-maker' : '/wedding-ceremony-timeline-maker'}>{ceremony ? 'Wedding reception timeline' : 'Wedding ceremony timeline'}</Link></p></div></section><Footer /></main>;
}
